### PR TITLE
Add base font-size

### PR DESCRIPTION
**Pull request by dennisroethig**
### Overview
This adds a base font-size (`font-sizes/size2`) to avoid inherited font-size-styles being used (e.g. in headings). As this might break existing pills which rely on inherited font-size-styles, I'm going to create a major-release

### Preview
screenshot 2015-04-23 11 30 13

### CODE REVIEW

**Comment by andrewk** [comment]
LGTM :+1:

**Comment by xzyfer** [comment]
You're setting it, but are you using?

**Comment by dennisroethig** [comment]
Yes it's getting pulled in here: https://github.com/99designs/asimov-pill/blob/master/_mixin.scss#L24

Or am I missing something?

**Comment by xzyfer** [comment]
Cool I see it's already a thing but wasn't previously set - https://github.com/99designs/asimov-pill/blob/master/_mixin.scss#L24

**Comment by xzyfer** [comment]
:+1:

**Comment by xzyfer** [comment]
You're correct. I just expected you would need to add it to the mixin if wasn't already a settings.

**Pull request merged**
